### ISSUE TITLE
Improve Figure 2

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#10]
I printed out the paper.

The content of the current Figure 2 looks a bit small / unsharp.

Making it a bit wider would help.
Is it possible to hav ethe "go to map" above the spectrum, and then have the whole screenshot wider?

If no, I'd suggest to crop it and just show the content a bit larger.

Figure 1 is also a bit unsharp and the text in the popup not well visible. If you have the time, you could also re-do that one, by making a screenshot where popup and controls tak a bit more space.
Now that we have the extra Figure 5 that should be OK.

**Comment by vorugantia** [comment]
I made both the Map View and the Cat View images clearer. I printed them out to check and they look better, especially the Map View.
