### ISSUE TITLE
Selection of images in Table 1

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#11]
I've sorted the images in Table 1 according to waveband, it now looks like this:
https://github.com/gammapy/gammaskynet-gamma2016/blob/master/proceeding/tables/image_table.tex

The MWL data that's most relevant to compare with gamma-ray data is other non-thermal emission.
That means mostly radio and X-ray.

Currently there's no X-ray image.
Suggest you add one for ROSAT and XMM here (we can add it to the webpage later).

**Comment by cdeil** [comment]
I think this is the best ROSAT image they have:
http://cade.irap.omp.eu/documents/Ancillary/4Aladin/RASS/

**Comment by cdeil** [comment]
For XMM Newton it's this one:
http://skies.esac.esa.int/XMM-Newton/EPIC-RGB/

Yes, the X-ray images don't look so nice.
But they are the most relevant for gamma-ray astronomy, because hard X-ray emission is nonthermal emission, i.e. also shows the cosmic particle accelerators.

There is no great X-ray survey yet.
We could mention that e.g. http://www.mpe.mpg.de/eROSITA will be available in the coming years and then also some day on gamma-sky.net.

**Comment by cdeil** [comment]
If you want to mention more future data and surveys, you could also mention that CTA is coming and will do nice surveys of the TeV sky:
http://adsabs.harvard.edu/abs/2013APh....43..317D

**Comment by vorugantia** [comment]
- ROSAT image added to Image Table.
- XMM-Newton image added to Image Table.
- Referenced CTA in the introduction.

But I did not mention that http://www.mpe.mpg.de/eROSITA (yet).

Closing this issue...
