### ISSUE TITLE
Wording in the "features" section

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#12]
In the features section you currently talk about "analysis tools" for the catalog view.

I don't consider anything there "analysis".

One can "select" a source and display it's properties / images of it's spectra / lightcurves.

Analysis would be to fit the spectra, run algorithms on the lightcurve to try an assess if it's variable, ...
As I said, I do not think we have the manpower to build such "analysis" features into gamma-sky.net . We would have to go to a website with a Java or Python backend, implement a ton of GUI stuff ... a huge project.
And it would always remain limited to pre-built functionality, wouldn't be used much.

Instead, we should present "gamma-sky.net" as the "explore" and "browse" part for the gamma-ray sky, and for analysis point to Gammapy / the IPython notebooks / Binder.

@vorugantia - Can you make a change in this direction?
Concretely, I think it could just be "Catalog view:" instead of "Analysis tools in the catalog component:". Although probably some other changes in the text to make this scope of gamma-sky.net clearer.

**Comment by vorugantia** [comment]
Wording has been fixed in the Idea, Features, and Outlook sections.
