### ISSUE TITLE
Figures 3, 4, 5

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#14]
Usually all Figures / tables should be referenced from the main text. It's very uncommon to never mention a figure or table, and I think considered bad style, because you're supposed to discuss them and guide the reader to look at them at the right place.

I think Figures 3, 4, 5 are never referenced and we need to add a paragraph somewhere?
@vorugantia - Is that right? Do you have a suggestion?

Also:
- What's the best order for Figures 3, 4, 5? Maybe do all-sky, galactic plane, Cygnus? Or put Galactic plane first because it's nicest?
- The captions of Figures 3, 4, 5 should also be a bit extended. If the FOV is not square, it should be given as width x height (doesn't have to be super precise). At least for the Galactic plane figure, the markers should be mentioned ... it's scientifically interesting to know where gamma-ray sources or SNRs are ... this is kind of the "science application" I was suggesting to have in the paper.

**Comment by vorugantia** [comment]
- I'm ordering Figures 3, 4, and 5 as: all-sky, galactic plane, Cygnus. It is also the order they are referenced in the text.
- Added width x height measurements for the galactic plane and Cygnus region.
- Figure 3 mentioned in Data section.
- Figures 4 and 5 mentioned in Idea sections.
