### ISSUE TITLE
Why a new webpage?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#15]
I think we should try to motivate more why we created a new webpage for the gamma-ray sky in the introduction or idea section.
- Why not use Google Sky or World Wide Telescope and create more content there?
- Or why not just add gamma-ray HIPS images at CDS and gamma-ray-relevant catalogs on Vizier and look at the results on Vizier?

It's not very hard to explain / motivate why we started a new project / website:
- authoring content for Google Sky or WWT is complex. They don't use HIPS, and HIPS is becoming an astronomy standard and is getting more and more popular, and there's an open-source tool to generate it from FITS images. Also it's not clear if implementing the catalog / source view with the search field and per-catalog view would even have been possible.
- just using Vizier doesn't give us the option to implement the "catalog view" we want, i.e. have something like Figure 2. It also doesn't give us the option to have "pre-arranged" view of the most useful information, like the default image and catalogs visible in the map view.

So I think a paragraph should be added to the introduction or ideas section that mentions Google Sky and WWT and very briefly why we decided to make a new webpage.

**Comment by vorugantia** [comment]
I further explained this idea in the Introduction, but please refine the motivation statement if anything is missing.
