### ISSUE TITLE
Add info that website is "static" and where catalogs are loaded

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#16]
A key feature of our website is that it is a "static website", i.e. doesn't have a Python or Node or Ruby backend server process that generates content / pages / catalogs / images / anything on request.

This allows us easy and for-free deployment on GH pages, no security issues.
It also has drawbacks of course, e.g. we don't have user "sessions" where they can bookmark sources and view and images they like, and no analyses on gamma-sky.net.

But overall, by choosing a static website technology, we make the website easy to implement, maintain, deploy and I'm sure it was the right choice for the project. We should also explain that we can handle "big datasets" like very large survey images and very large catalogs by using HIPS ... the JS client only downloads static assets (tiles, catalog sub-parts) as needed, also the CDS HIPS server is just a static web server.

Concerning the catalogs, we should explain that we're converting them from FITS to JSON as part using a Python script as part of the static website build step.

There's also the aspect that we have two "live" catalogs that are frequently updated: SNRcat and the TeV cat. There's two options: bundle a recent version of the catalog and serve it from our server, or fetch it directly from SNRcat / gamma-cat. I think we should mention this, and say that, at least for now, we have decided to serve all catalogs as JSON from our website (requiring us to update it from time to time, but making our webpage self-contained, i.e. not break if the other page is down or changes the format).

@vorugantia - Can you try to add some info to explain this better? For the "static website" aspect, probably to the implementation section, and for the catalogs, maybe also there or in the data section where you talk about the catalogs.

**Comment by cdeil** [comment]
If you're going over the 6 page limit by adding some sentences here and there with my requests, I would prefer to change features section from bullets to small paragraphs to save space, or to even throw out the Cygnus image, instead of not mentioning these things.

**Comment by vorugantia** [comment]
Static webpage and FITS -> JSON described in more detail in Implementation section.
