### ISSUE TITLE
Too many pages

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gammaskynet-gamma2016#17]
EDIT: I managed to fit it into six pages by removing some unimportant footnotes in the Idea section. But adding just another line of text to page 2 will push everything to 7 pages again. So if you add any text to the second page, try to see if something can be cut/mentioned in some other part of the paper to stay at the 6 page limit.

Otherwise, see options below for other ways to cut down pages:
- Make Features section a paragraph instead of bullet points
- Make Figures 4 and 5 smaller ( `\includegraphics[scale=...]` )
- Remove Figure 4 or 5 (only if we have to)

I would prefer the second way because I really like the bullet points, it breaks up the long text from the other sections.

Close this issue once we are definitely clear of the 7 page mark.

**Comment by cdeil** [comment]
OK. Agreed we can just make the Figures a little smaller if we have to.
Closing this issue now.
