### ISSUE TITLE
Review idea section

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#19]
- [x] "displays overlays of MWL survey images" -> "displays gamma-ray and MWL survey images" (focus is on gamma-rays, and we have no "overlays" feature to show several maps at the same time yet, e.g. as contours or blending image layers)
- [x] Paragraph starting with "The motivation ...": "open-source dataset" -> "open dataset"

Also, like I said before, don't promise that we will expose "all newly developed surveys" ... we currently have one image and three gamma-ray catalogs, we just pick the most important ones / of most interest to us ... we will never show "all gamma-ray data" on gamma-sky.net. Also like I said for the intro, wording like "We serve data in a widely accepted format ..." sounds like we offer all data for download. This is not what we're doing, at least not currently. We don't offer any files for download, but we take some public datasets and present them in a form so that they can easily be browsed and explored.
We might offer gamma-ray data for download in the future, but for now we just display public data from three gamma-ray catalogs that are available for download elsewhere:  https://github.com/gammapy/gamma-sky/wiki/Datasets#catalogs

The main "idea" is: astronomer wants to quickly find out what's known about a given gamma-ray source, or about the gamma-ray sources in a given region. Until now this was painful, they had to download FITS files and fiddle around for quite some time. Now they can just go to gamma-sky.net and find out quickly. The (once routing to a given map view works) they can "share" that view with a colleague by sharing a URL link.

This is how I would describe it. For now, I wouldn't even mention that gamma-sky.net is a place to download gamma-ray data. That might come in the future or it might not, but for now it is not that place.

**Comment by vorugantia** [comment]
See fixes [here](https://github.com/gammapy/gammaskynet-gamma2016/commit/2ce4504fc14072a1829fe2c4f8419ed0de468ba5).
