### ISSUE TITLE
Feedback data section

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#21]
- [x] Define the abbreviation SNR = "Supernova Remnant"
- [x] For gamma-cat I'd prefer you link to the Github repo. I don't know yet if we'll keep showing a catalog at gammapy.github.io/gamma-cat .
- [x] The URLs for SNRcat and gamma-cat are in Table 2. Suggest to remove them from the main text to avoid the duplication and save space
- [x] Suggest to remove the sentence "The university of Manitoba maintains ...". Samar and Gilles maintain it, and I think Gilles has already moved to another university.
- [x] I see you talk about SESAME now. I think I would just move this last paragraph to the map / Aladin Lite features section. If you consider the databases that back up SESAME to be part of the "data" that needs to be described for gamma-sky.net, OK. I'd still suggest you mention SESAME in the maps features though.

**Comment by cdeil** [comment]
I would remove the last sentence that some images are currently fetched from 3FGL-table.
That was just a temp solution to have something to show in the group meeting, and it's not live at gamma-sky.net.

They don't even have 2FHL plots there, we'll just write a script to make both 2FHL and 3FGL plots for gamma-sky.net and serve the PNGs ourselves.
(see https://gammapy.readthedocs.io/en/latest/spectrum/plotting_fermi_spectra.html)

It'll also be good to have this single-sentence paragraph on the next page gone for paper structure.

I do think we should link to "3FGL-table" somewhere, like we do from
https://github.com/gammapy/gamma-sky/wiki/Other-projects
In the paper this could either be in the intro, in a section mentioning "other projects" like 3FGL-table or WWT or Google Sky or TeVCat and why we still decided to do a new webpage.
Or you could mention "3FGL-table" in the outlook section when discussing features we want to add, e.g. selecting sub-classes of sources like "SNR" or "Galactic" or "blazar" or "UN-ID".

**Comment by vorugantia** [comment]
See fixes [here](https://github.com/gammapy/gammaskynet-gamma2016/commit/f3338a300bcd6b2f3b4920900b18072399ea5ad0).

We mention that the SNRcat database is maintained by Gilles and Samar - should we say the same for gamma-cat, that you maintain it? Or did you want me to remove this "database is maintained by..." sentence altogether?

I didn't make an "other projects" paragraph in the Intro like you suggested. I'll open an issue in case you still want to do so.

**Comment by cdeil** [comment]
Thanks for implementing all the suggestions.

> We mention that the SNRcat database is maintained by Gilles and Samar - should we say the same for gamma-cat, that you maintain it? Or did you want me to remove this "database is maintained by..." sentence altogether?

Keep as-is now, or remove the sentence who maintains it.
I just found it weird to say that the university of Manitoba maintains it.

No need to mention who maintains gamma-cat.
