### ISSUE TITLE
Feedback implementation 

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#22]
- [x] Suggest to add a link to https://angular.io/ when mentioning Angular 2
- [x] The sentence "The website is being hosted by Github pages" from the "status and outlook" section should be moved to the "Implementation" section. It's one of the major advantages for our "static website" implementation: free hosting by Github pages. (and static pages are super-fast ... if our webpage becomes popular Github will keep serving it for free and very fast I think, if we had a server backend it would quickly become expensive to host gamma-sky.net if it becomes popular

**Comment by vorugantia** [comment]
See fixes [here](https://github.com/gammapy/gammaskynet-gamma2016/commit/109d260c8cfff931557195e51e28e56dc704a57a).
