### ISSUE TITLE
Feedback status and outlook

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#23]
It's OK as-is, but if you have time, this would be my feedback: currently it's very generic, doesn't give much info.

You could mention some concrete plans (see https://github.com/gammapy/gamma-sky/issues), like implementing "map share URL" or adding Google analytics so that we know if / how the page is being used, or adding the Fermi high-energy images. 

Concerning status, I'd suggest to not say anything. Let's just try to get a solid version together (Angular 2.0, gamma-cat as TeV, some more info and spectra / lightcurves for Fermi, Google analytics) and then "launch 1.0" it soon. Describing status more precisely now in the proceeding or trying to give a date for "launch 1.0" isn't useful.

**Comment by vorugantia** [comment]
See fixes [here](https://github.com/gammapy/gammaskynet-gamma2016/commit/ef150d0c54a083a0dca02b1a682094cbe5f129d9).
