### ISSUE TITLE
"Other projects" paragraph in intro?

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gammaskynet-gamma2016#24]
@cdeil mentioned the possibility of making an "other projects" paragraph in the intro section to mention the 3FGL table, WWT, Google Sky, and/or TeVCat, and why we still decided to do a new webpage. Should we still add this paragraph?

**Comment by cdeil** [comment]
Either way is fine. Maybe leave as-is and submit?

**Comment by cdeil** [comment]
I saw your comment on Slack now. I'm submitting it to Frank now.
