### ISSUE TITLE
Look up angular resolution for images

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gammaskynet-gamma2016#4]
This is a reminder issue to look up the angular resolution for each of our images we mention in the table. The HiPS database does not list the correct resolution. For example, the angular resolution for Haslam 408 image can be found in [its paper](http://adsabs.harvard.edu/cgi-bin/bib_query?1982A&AS...47....1H).

**Comment by vorugantia** [comment]
@cdeil - Look at pages 19-20 of this paper:

https://arxiv.org/pdf/1505.02291.pdf

In their list of HiPS images, they have the angular resolution of **all of our website's images** except Haslam 408 (but you already looked up that angular resolution for me).

Are these accurate and should I add them to the paper? Also, do you think we should have another column in our table for sky coverage %, like they did in this paper? Or maybe we can add back a "Description" column for each survey and just use the ones from this paper?

**Comment by cdeil** [comment]
You mean the theta_pix column?

I think that's the pixel size for the maximal zoom level, no?
That's different from the angular resolution of the survey.

E.g. for Fermi they have 6 arcmin = 0.1 deg, but the Fermi PSF in that energy range is a few degrees.
So at the highest zoom-level, they have oversampled the image, which isn't bad, but also not super relevant.

If we give that resolution, it should be in addition to the intrinsic survey resolution.

**Comment by vorugantia** [comment]
I see. Yes, those numbers didn't make sense for angular resolution.,

**Comment by vorugantia** [comment]
Along with looking up the angular resolution values for our image data, we also need to fill in the "band" column and find the frequency band for each image. Either we do this or we just cut out the columns with empty cells.

**Comment by cdeil** [comment]
I would suggest to radically simplify that table.
Just have the name and then a one-line comment after describing it a bit.

The main point to get across with the table that there are images of interest that show non-thermal emission
- radio (planck)
- X-ray (ROSAT, but also XMM)
- Fermi-LAT

and then maybe to mention one or two more that you use for the later Figures.

**Comment by vorugantia** [comment]
Okay, I made changes to the table and made a commit in the open PR. I'll keep working a bit today and then I'll merge the PR in the evening.

Also, we aren't currently showing a ROSAT x-ray survey (or any other x-ray image) right now on gamma-sky.net, but it's in the HiPS database: http://alasky.u-strasbg.fr/ROSATWFC-new/ROSAT-WFC-color/

Do you want me to still add it to the Image Table? And then next time we update the website we can add the ROSAT survey image.

**Comment by vorugantia** [comment]
Tables have been reformatted and x-ray images added. The angular resolution and band columns were cut out. Instead, information is just in a "Description" column.
