### ISSUE TITLE
Image/Table placement

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gammaskynet-gamma2016#8]
We have a few issues with image placement. I don't really understand how the placement works so I couldn't manage to fix this issues on my own. Maybe I can try again tomorrow.
1. The last image in the paper cuts between the "References" section and it shouldn't (I think)
2. Figure 1 and Table 1 appear in the document before they're mentioned in the text itself. Should they be pushed to somewhere further along the paper?
3. I was thinking that we put Figure 1 and Figure 2 right next to each other on the same page, one above the other. Any thoughts on this?
4. I think both Figure 1 and Figure 2 should come first, then Table 1 and Table 2. Right now it's Figure 1, Table 1, Figure 2, Table 2.

**Comment by cdeil** [comment]
I can do the image placement ... assigning to myself.
Please ping me again here if I haven't done this by Thursday evening (Heidelberg time).

**Comment by cdeil** [comment]
I tried the LaTeX Figure placement for half an hour, and couldn't find a solution.

I agree that what we want is this:
- Figure 1 and 2 on top of each other at the top of page 2
- Table 1 and 2 on top of each other at the top of page 3
- The other Figures later, no problem there.

@joleroi - Do you know how to do it or spend some time trying to figure out how to do it with LaTeX?
If no, please assign back to me and I'll "research" this further tomorrow.

**Comment by cdeil** [comment]
Actually, if we don't find a solution for this, I think we can just keep the Figure / table placements as-is, they look better now:
https://github.com/gammapy/gammaskynet-gamma2016/blob/master/proceeding/gammaskynet-gamma2016.pdf

Page 2 has sky view screenshot followed by image table.
Page 3 has catalog view screenshot followed by catalog table.

I still think both Figures on page 2 and then both tables on page 3 would be slightly better, but not by much and I'm not sure we should spend time on figuring out this LaTeX issue, unless @joleroi, you know how to do this off the top of your head.

Close issue?

**Comment by cdeil** [comment]
@vorugantia - Close this issue and focus on the others concerning content?

I think the placements are very nice now, and we should focus on explaining
- why did we make a new webpage?
- scope: gamma-sky.net is for exploration / browsing. For analysis we're suggesting to use IPython / Gammapy and are working on implementing analysis features there.

I have to go now, but I'll have a final look at the proceeding tomorrow.

**Comment by vorugantia** [comment]
Alright. I agree the image placements are better now. I'll reopen the issue if, when we add text, the image placement changes and looks worse.
