### ISSUE TITLE
Reminder: Order References in order mentioned

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gammaskynet-gamma2016#9]
Just a reminder for me to make sure all references are ordered by when they're mentioned in the paper.

**Comment by cdeil** [comment]
LaTeX orders the references at the end automatically, no?

I don't understand.
Can you point out one thing in the paper where you think the order should be changed?

**Comment by vorugantia** [comment]
I can only find this issue for Table 2 - in the code, we mentioned the table before the text under the Idea section, but since LaTeX is displaying the text first and the table further in the document, the references appear out of order.

If you just fix the table/figure placements, the problem should be fixed.

**Comment by cdeil** [comment]
I don't think this matters, it's OK.

Yes, having references to figures and tables in numerical order in the text would be nice.
But referencing figures and tables where it makes most sense, and also positioning the figures and tables in the paper nicely (see #8 ) is more important.

So I'm closing this issue.
@vorugantia - If you'd still like to change something, feel free to re-open and let me know if I should do something.

**Comment by vorugantia** [comment]
What if we just removed the references from Table 2? Because those three references already come in the Data section. I think that would allow all references to be numbered in order in our current placement of text and figures.

They also said they want chronologically ordered references here: https://www.mpi-hd.mpg.de/hd2016/pages/proceedings.php

**Comment by cdeil** [comment]
Sorry, I'm still confused where in the paper you see something that's out of order and whether it really matters. Can you please post a screenshot?

(yes, removing the citations from table 2 is possible. But it's kind of nice to have them there, no?)

**Comment by vorugantia** [comment]
Bottom of page 2 (introduction text) with references [6] [7] and [8]:

![bottom_page_2_intro](https://cloud.githubusercontent.com/assets/18579919/18998668/a4fda546-8707-11e6-9976-a198223af67c.PNG)

Table 2 on page 3 with references [3] [4] and [5]:

![page_3_table2](https://cloud.githubusercontent.com/assets/18579919/18998670/a679dd86-8707-11e6-9e1f-e27ca7b56988.PNG)

I'm not sure if ordering them in the order they appear in the paper is important either, I just saw the note in the submission guidelines for Gamma-2016 (https://www.mpi-hd.mpg.de/hd2016/pages/proceedings.php). It says they want references to show in order of appearance. But if it is fine like this regardless, we can just leave it.

**Comment by vorugantia** [comment]
I think this is fine and not worth worrying about. It probably doesn't matter if references are out of order.
